# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monkey_hd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='ticket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='monkey_hd.Ticket'),
            preserve_default=False,
        ),
    ]
